### ISSUE TITLE
Doom source ports error

### ISSUE THREAD

**Issue by actraiser30** [Exarkuniv/RetroPie-Extra#185]
Hi there 

These three doom ports are failing to install

Chocolate doom get an error in compiling 
Chocolate strife not found

Crispy doom gets the error crispy doom not found

And eternity gets the error eternity not found

I assume pr-boom does the same haven't try that one

All tested in a Pi4 with Raspbian buster Retropie image

Thanks

**Comment by Exarkuniv** [comment]
if you could provide a log file of either or all. it would help. 
it will be a bit before i get my pi4 back for testing

**Comment by actraiser30** [comment]
No worries,will try to make them work and get back to you.

**Comment by actraiser30** [comment]
Hello i found whats wrong its the sdl version retropie installs version 2.0.10 while the chocolate doom requires at least 2.0.14
what i did is:

Installed sdl 2.0.14
Installed chocolate doom without errors this time
removed sdl 2.0.14 (the game has no picture with this version of sdl it only has audio)
uninstall sdl 2.0.14
installed sdl 2.0.10
re-install chocolate doom and stop the installation after it installs the sdl2 missing libraries
run the game

its complex to do all this,the best thing you can do is add to the script to install the last branch before they change the sdl 2.0.10 to a higher version

i assume the other scripts have the same issue 

Crispy doom,eternity and pr-boom

**Comment by Exarkuniv** [comment]
pr-boom installs just fine as is

i have fixed chocolate doom, Crispy doom due to the SDL error
Eternity error was not caused by the SDL, but something else they changed

thanks for taking the time to check these and also figure out what the issue is. 

once the new image comes, these will be changed back to pulling the latest 
since the new image will be build on bookworm
