### ISSUE TITLE
pi5 - AetherSX2 can't start bios / Open data directory fails

### ISSUE THREAD

**Issue by ChristianKa** [Exarkuniv/RetroPie-Extra#188]
Raspberry Pi 5 8 GB
Installed AetherSX2 via RetroPie-Extra
AetherSX2 starts and lists the games it found in the correct location.
kernel=kernel8.img was set in boot/firmware/config.txt

Issue 1: BIOS not starting
I placed the bios files in
/pi/RetroPie/BIOS/ps2/
set the location in the Settings and selected the bios file, but everytime I start any game the error "aethersx2 requires bios to run". Same when I try to start the BIOS via the menu. 

Issue 2: Failed to load URL
And when I try "Tools/Open Data Directory" I get another error saying "failed to load URL" and it seems to be looking for this - non excisting - folder
/home/pi/.config/aethersx2/

Is there something I'm missing when trying to start the BIOS?
And how can I re-route the data directory from /home/pi/.config/aethersx2/" to e.g. "/home/pi/RetroPie/BIOS/ps2/aethersx2/"?

Thanks!

**Comment by Exarkuniv** [comment]
Did you try it with out setting the location for the bios files

We have a symbolink for that folder and you don't have to do anything just put the bios files in the folder.

If you did that. Then you have bad bios files. I know it took me a bunch to get the right one 

As for the tools dir.
There nothing we can do about that. The program is no longer being developed and was never really ment for the pi. We just happened to get it working.

**Comment by ChristianKa** [comment]
Thanks for your quick reply! Have uninstalled everything and just put a 'bios' folder with the bios files in the automatically created RetroPie/BIOS/ps2 location (so the files were at RetroPie/BIOS/ps2/bios/) 
If I check in AetherSX2 System/Settings/BIOS it finds the folder and lists the bios correctly, so everything looks good in theory. 

Tried the two recommended bios file sets (SCPH-90001 and SCPH-70012) and two other ones. 
But still with every start of a game I get the 'aethersx2 requires bios to run' error dialog.

I'll keep trying with other files.

If you happen to know the name of a bios that works I'd really appreciate it.

**Comment by Exarkuniv** [comment]
Unfortunately I'm on not going to be back my pi for a few weeks. Once I am and you still need it I'll let you know

**Comment by ChristianKa** [comment]
Tested and still same result. Then uninstalled AetherSX2 and Retropie-Extras, reinstalled and started with that bios file in the correct folder and still get the message "Startup Error - AetherSX2 requires a PS2 BIOS in order to run (...)"

In AetherSX2 GUI Settings/BIOS the file is listed, recognized and highlighted, but it doesn't want to start.

I saw that the BIOS was Europe region, so I tried with four other EU roms as I've used US roms before. Unfortunately same message so we can rule a region issue out as well...

**Comment by Exarkuniv** [comment]
Hmm
It has been tested by a few other people and it worked so I don't know what else it could be. 

And since it's already complied and no longer maintain the program being the issue is ruled out. 

I'll try it again once I'm back from vacation with a fresh build and see if some else changed

**Comment by Exarkuniv** [comment]
so i did a clean image and it works as it should for me. 

sorry not much i can do with this, until there is a standard image that we all use. its hard to trouble shoot whats going on, since there are different ways to install RetroPie on different version of PieOS

**Comment by ToxicYDG** [comment]
Hi, I am running into the same issue.

here are the steps I followed to install AetherSX2 on my pi5. Could you please provide your steps of installation to verify if anything was missing?

1. Installed Rapian lite 64-bit
2. Manually installed retropie
3. installed Retropie-extras
4. kernel=kernel8.img was set in boot/firmware/config.txt
5. Installed AetherSx2 through Retropie-Setup
6. Placed bios in /brendan/RetroPie/Bios/
7. Placed Roms in /brendan/RetroPie/Roms
8. Launched the rom

I immediately get the "AetherSX2 requires a BIOS file to run" Error. My ROMS and Bios path is correctly set, and AetherSX2 can see the files.

The issue is that the "Open Data Directory" Tool fails to open. The path is /home/Brendan/.config/aethersx2
![IMG_1097](https://github.com/Exarkuniv/RetroPie-Extra/assets/10162235/b4a6fbf8-d47d-4e76-a077-e43a9ce566f6)

When I open this folder on the Pie through SSH it instead takes me to /opt/retropie/configs/ps2/. Could there be a problem with the linked folder?
<img width="407" alt="Screenshot 2024-06-22 at 1 58 47 PM" src="https://github.com/Exarkuniv/RetroPie-Extra/assets/10162235/05848809-df43-41f2-bfde-a2bb4465aa1a">



If not do you know of a way to manually change the path that the "Open Data Directory" tool looks for?

**Comment by Exarkuniv** [comment]
you have to put the bios files in the PS2 file in the bios folder

And no for whatever reason you can't change the location with the menu I have tried.

"If not do you know of a way to manually change the path that the "Open Data Directory" tool looks for?"

No I don't know what it's looking 
And since this program is already precompiled and no longer being maintained or supported or worked on it's never going to be fixed. 


Which is the reason why we have a symbol link from the location it looks at to the bios folder

When I closed this issue I did a clean image following 
https://github.com/danielfreer/raspberrypi5-retropie-setup
And it worked as it has before

**Comment by Vatzz** [comment]
> Hi, I am running into the same issue.
> 
> here are the steps I followed to install AetherSX2 on my pi5. Could you please provide your steps of installation to verify if anything was missing?
> 
> 1. Installed Rapian lite 64-bit
> 2. Manually installed retropie
> 3. installed Retropie-extras
> 4. kernel=kernel8.img was set in boot/firmware/config.txt
> 5. Installed AetherSx2 through Retropie-Setup
> 6. Placed bios in /brendan/RetroPie/Bios/
> 7. Placed Roms in /brendan/RetroPie/Roms
> 8. Launched the rom
> 
> I immediately get the "AetherSX2 requires a BIOS file to run" Error. My ROMS and Bios path is correctly set, and AetherSX2 can see the files.
> 
> The issue is that the "Open Data Directory" Tool fails to open. The path is /home/Brendan/.config/aethersx2 ![IMG_1097](https://private-user-images.githubusercontent.com/10162235/341988442-b4a6fbf8-d47d-4e76-a077-e43a9ce566f6.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTU0NzcsIm5iZiI6MTcyMjQ5NTE3NywicGF0aCI6Ii8xMDE2MjIzNS8zNDE5ODg0NDItYjRhNmZiZjgtZDQ3ZC00ZTc2LWEwNzctZTQzYTljZTU2NmY2LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZmY3YjM5Yjc3MGVlYTM0OGE2ZTliZDIyNGQ5ZTdlYWEzMDVmMWZiOTdhM2U2ZGRmYWExNjVjZDZmOWE4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Le5YztjgADTpt5NQA0YTo-TNpiM9XfXN6P-xI3eVVB8)
> 
> When I open this folder on the Pie through SSH it instead takes me to /opt/retropie/configs/ps2/. Could there be a problem with the linked folder? <img alt="Screenshot 2024-06-22 at 1 58 47 PM" width="407" src="https://private-user-images.githubusercontent.com/10162235/341988495-05848809-df43-41f2-bfde-a2bb4465aa1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTU0NzcsIm5iZiI6MTcyMjQ5NTE3NywicGF0aCI6Ii8xMDE2MjIzNS8zNDE5ODg0OTUtMDU4NDg4MDktZGY0My00MWYyLWJmZGUtYTJiYjQ0NjVhYTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MmRmNzJhYmUzMmUxNzUyNmE3ODU4MTYwZWE0NWM3MmYyNzIwZGU3NmM1YmM2ZjQyNGZkYWZlNzJjNGZiZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdjyLAbdj3BsrpynQCDatqqQNz2fZnCiH6Wk-fqCkOg">
> 
> If not do you know of a way to manually change the path that the "Open Data Directory" tool looks for?

I know this is closed, but I came here searching for a solution and managed to fix the issue so though I would post the fix.

My issue why it couldn't find the BIOS was because I had chosen a username for rasberry pi os other than pi so the symlink was going to a different directory. Fix is either do your own symlinks or just reinstall from scratch like I did.

I can see in your photo that your username is brendan from the link so the symlink won't work.

**Comment by ChristianKa** [comment]
Thanks guys, I bet this was the same problem with my install as I had a custom name instead of pi too.
