### ISSUE TITLE
Unreal T99 64bit

### ISSUE THREAD

**Issue by actraiser30** [Exarkuniv/RetroPie-Extra#224]
Hi

How can this port work?

Since there isn't any 64bit Retropie image

Thanks

**Comment by Exarkuniv** [comment]
Not sure what you are asking.

It works just fine.
As for RetroPie. You just manually install it on bookworm

**Comment by actraiser30** [comment]
The port is 64bit,On 64bit bookworm you mean?

**Comment by Exarkuniv** [comment]
Yes, since that's what the next official image will be once it comes. Is going to be 64bit. For the pi5 for sure. And also probably the pi4. (Not 100 sure on that yet)

 Since 64bit on the pi4 is supported official from raspberry os

Unfortunately not every thing can be made to work on a 32bit OS. 
This is once of those cases.

**Comment by Exarkuniv** [comment]
closing this, as this is not really a issue, just a requirement of the programs
