### ISSUE TITLE
ecwolf diff not working

### ISSUE THREAD

**Issue by Exarkuniv** [Exarkuniv/RetroPie-Extra#88]
the .diff for ecwolf is no longer applying to the correct file so the esc key is not there.

need to learn how to make a diff and see whats going on with that.

the rest of the script works fine

**Comment by s1eve-mcdichae1** [comment]
I'm not sure if this is necessary any longer. Besides some reformatting to line up the columns, this patch only seems to add two lines, to bind the Pause and Escape keys.

The current code already has a Pause keybind now so that one isn't necessary anymore. And Escape also seems to be included, hard-coded to the Start button, which can't be assigned to any other function.

https://github.com/s1eve-mcdichae1/RetroPie-Extra/commit/d41e85818938f5dd441f7679f568f4e867baf335

I made a patch [here](https://github.com/s1eve-mcdichae1/RetroPie-Extra/commit/d41e85818938f5dd441f7679f568f4e867baf335) that restores the Escape option in the key binds if you want to give it a whirl anyway. Maybe this is useful if you have a non-standard controller where Start isn't recognized? But as far as I can tell on my Logitech, the only thing it does is allow me to map a second "Start" button, in addition to the actual Start button.

**Comment by Exarkuniv** [comment]
yeah i was confused on what changed with the diff other then the add of the new lines, i thought there was a few things that where changed, but i never knew why since they could always be remapped in the menu. 

i think i needed to have the ESC key for my 8bitdo, but its been awhile. i will gladly give it a whirl

**Comment by Exarkuniv** [comment]
give it a shot, got this
```
ecwolf patch /home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/ecwolf/01_keyboard_patch.diff failed to apply/home/pi/RetroPie-Setup
Errors:
ecwolf patch /home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/ecwolf/01_keyboard_patch.diff failed to apply
```

**Comment by s1eve-mcdichae1** [comment]
> ```
> ecwolf patch /home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/ecwolf/01_keyboard_patch.diff failed to apply
> ```

Aye. 'Member [this](https://github.com/Exarkuniv/RetroPie-Extra/blob/master/.gitattributes)? I think it's come back around to bite me in the ass. The **ecwolf** patch worked fine *until* I deleted my local copy & checked it back out from the repo, and then it no longer did work.

The initial patch, after I created it, had mixed DOS and UNIX line-endings. But after checking out from the repo, **git** (does what I told it to do and) strips the DOS characters, leaving only UNIX endings for every line. Turns out that that mixed-mode is important, in this case, as the patch wouldn't work as fully-DOS *or* fully-UNIX.

Will investigate. Probably a way around this, if not we might have to ditch the attributes file and make sure everything is formatted correctly at the source.

https://github.com/Exarkuniv/RetroPie-Extra/blob/master/.gitattributes

...try it now. I've modified the `.gitattributes` file to treat `.patch` and `.diff` files as binary and not to modify them (then I re-uploaded the patch, because it was still not working. I think it is now, though): https://github.com/s1eve-mcdichae1/RetroPie-Extra/commit/6b169c9d5d797c648bd7d38837afe006c24eb3a4

**Comment by Exarkuniv** [comment]
ok i will give that a shot.
if we need to drop the attributes thats fine, i just need to learn how to make sure everything is formatted right, lol

**Comment by Exarkuniv** [comment]
ok i used your ecwolf repo and was able to build and apply the patch fine, i also checked in game and there is a escape game key able to map. 

not sure if that was the problem or my system had a issue the first time. and your first patch was fine.

**Comment by s1eve-mcdichae1** [comment]
Yeah that was definitely the issue, I got the same "patch failed to apply" error after checking out from the repo.

With the change to `.gitattributes` and reupload the patch though, it seems to be working now. I'll go ahead and do a PR since it's (may be) required for some controllers.

**Comment by Exarkuniv** [comment]
> (may be) required for some controllers.

yeah, i cant remeber if 8bitdo needed it or not, i know it was a issue when the script was first made, but that was a few years ago. so now who knows. since it was not that hard, why not

thanks again for your help
